Repository joraeng-e/trip.zip, pull requests merged in 2024-07, with the labels that each got.

#1 📝 docs: pr 템플릿 수정
  .github/pull_request_template.md
Labels: 📝docs

#2 📦 chore: initial settings
  .eslintrc.json
  .husky/pre-commit
  .husky/pre-push
  package.json
  pnpm-lock.yaml
Labels: ✨feat

#3 📦 chore: fix version error
  package.json
  pnpm-lock.yaml
Labels: 🐛fix

#4 ✨ feat: 깃허브 액션 연동
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  build.sh
  package.json
  pnpm-lock.yaml
Labels: ✨feat

#5 🐛 fix: target branch develop으로 변경
  .github/workflows/deploy.yml
Labels: 🐛fix

#7 [JE-23] feat: husky commit lint
  .husky/pre-commit
  .husky/pre-push
  .husky/prepare-commit-msg
  package.json
  pnpm-lock.yaml
Labels: ✨feat, 🐛fix

#8 ✨ feat: 아이콘 등록
  public/favicon.ico
  public/icon/bedIcon.svg
  public/icon/calendarIcon.svg
  public/icon/deleteIcon.svg
  public/icon/facebookIcon.svg
  public/icon/instagramIcon.svg
  public/icon/kebabIcon.svg
  public/icon/minusTimeIcon.svg
  public/icon/notificationIcon.svg
  public/icon/passwordOffIcon.svg
  public/icon/passwordOnIcon.svg
  public/icon/plusTimeIcon.svg
  public/icon/profileAccountIcon.svg
  public/icon/profileCalendarIcon.svg
  public/icon/profileChecklistICon.svg
  public/icon/profileCogIcon.svg
  public/icon/starOffIcon.svg
  public/icon/starOnIcon.svg
  public/icon/twitterIcon.svg
  public/icon/xIcon.svg
  public/icon/youtubeIcon.svg
  public/imgs/empty.png
  public/logo/tripZip.png
  public/logo/tripzipFavicon.png
  public/next.svg
  public/vercel.svg
  src/libs/utils/Icon.tsx
  src/pages/index.tsx
Labels: ✨feat

#6 ✨ feat: api 타입 정의
  src/types/api/activities.d.ts
  src/types/api/auth.d.ts
  src/types/api/common.d.ts
  src/types/api/my-activities.d.ts
  src/types/api/my-notifications.d.ts
  src/types/api/my-reservations.d.ts
  src/types/api/users.d.ts
  src/types/index.tsx
Labels: ✨feat

#10 📝 JE-24-docs: pr 템플릿 이슈넘버 삭제
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: 📝docs

#11 📦 JE-26-chore: test setting
  .eslintrc.json
  __tests__/components/.gitkeep
  __tests__/pages/.gitkeep
  __tests__/utils/.gitkeep
  jest.config.js
  jest.setup.ts
  package.json
  pnpm-lock.yaml
Labels: ✨feat

#12 📦 JE-27-chore: tailwind setting
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 📦 chore

#13 ✨ JE-28-feat: classnames 라이브러리 구현
  __tests__/utils/.gitkeep
  __tests__/utils/classnames.test.ts
  src/libs/utils/classNames.ts
  src/libs/utils/index.tsx
Labels: ✨feat

#14 🐛 JE-29-fix: 아이콘 에러 수정
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icon/paperPlane.svg
  src/libs/utils/Icon.tsx
  src/pages/_document.tsx
Labels: 🐛fix

#15 ✨ JE-10-feat: input 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/input/Input.tsx
  src/components/input/PasswordInput.tsx
  src/components/input/Textarea.tsx
  src/libs/utils/schema.ts
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨feat

#17 ✨ JE-32-feat: instance 초기 설정 및 api 함수 생성
  src/libs/api/activities.ts
  src/libs/api/auth.ts
  src/libs/api/index.tsx
  src/libs/api/myActivities.ts
  src/libs/api/myNotifications.ts
  src/libs/api/myReservations.ts
  src/libs/api/user.ts
  src/libs/axiosInstance.ts
Labels: ✨feat

#19 📦 JE-33-chore: ts 버전 수정(^5)
  package.json
  pnpm-lock.yaml
Labels: 📦 chore

#18 ✨ JE-9-feat: button
  package.json
  pnpm-lock.yaml
  public/icon/paperPlane.svg
  src/components/button/index.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨feat

#22 ✨ JE-16-feat: 헤더 구현
  src/components/Header/_components/LoggedInHeader.tsx
  src/components/Header/_components/LoggedOutHeader.tsx
  src/components/Header/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ✨feat, 💄ui

#21 ✨ JE-30-feat: layout
  src/components/pageLayout/pageLayout.tsx
  src/pages/_app.tsx
Labels: ✨feat

#26 🐛 JE-42-fix: 버튼 에러 수정
  src/components/button/index.tsx
Labels: 🐛fix

#24 ✅ JE-40-test: 버튼 테스트 코드 작성
  __tests__/components/Button.test.tsx
Labels: 📝docs

#27 💄 JE-41-ui: 프로필 사이드 바 UI 구현
  public/icon/pencil.svg
  public/icon/profileAccountIcon.svg
  public/icon/profileCalendarIcon.svg
  public/icon/profileChecklistICon.svg
  public/icon/profileCogIcon.svg
  public/imgs/baseProfile.svg
  src/libs/utils/Icon.tsx
  src/pages/mypage/_components/ProfileSideBar.tsx
  src/pages/mypage/index.tsx
Labels: 💄ui

#25 ✨ JE-14-feat: 회원가입 페이지 구현
  .github/workflows/deploy.yml
  __tests__/pages/.gitkeep
  __tests__/pages/signup.test.tsx
  package.json
  pnpm-lock.yaml
  src/components/Header/_components/LoggedInHeader.tsx
  src/components/Header/index.tsx
  src/components/button/index.tsx
  src/components/input/Input.tsx
  src/components/input/PasswordInput.tsx
  src/components/input/Textarea.tsx
  src/libs/api/user.ts
  src/libs/utils/authSchema.ts
  src/libs/utils/schema.ts
  src/pages/_app.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
Labels: ✨feat

#23 ✨ JE-12-feat: modal 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/Modal/Close.tsx
  src/components/Modal/Content.tsx
  src/components/Modal/Description.tsx
  src/components/Modal/Root.tsx
  src/components/Modal/Title.tsx
  src/components/Modal/Trigger.tsx
  src/components/Modal/index.tsx
  src/types/modaltype.ts
  tailwind.config.ts
Labels: ✨feat

#30 ✨JE-43-feat: KakaoMap, Daum Postcode 구현 및 적용
  package.json
  pnpm-lock.yaml
  src/components/KakaoMap.tsx
  src/components/button/index.tsx
  src/libs/constants/kakaoscript.ts
  src/pages/test.tsx
  src/types/images.d.ts
Labels: ✨feat, 💄ui

#31 ♻️ JE-46-refactor: 폴더 구조 정리
  __tests__/components/Button.test.tsx
  __tests__/components/Pagination.test.tsx
  src/components/activities/SearchBox.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Footer/index.tsx
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Header/_components/LoggedOutHeader.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/PasswordInput.tsx
  src/components/commons/Input/Textarea.tsx
  src/components/commons/KakaoMap/index.tsx
  src/components/commons/Modal/Close.tsx
  src/components/commons/Modal/Content.tsx
  src/components/commons/Modal/Description.tsx
  src/components/commons/Modal/Root.tsx
  src/components/commons/Modal/Title.tsx
  src/components/commons/Modal/Trigger.tsx
  src/components/commons/Modal/index.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/commons/Pagination/Buttons.tsx
  src/components/commons/Pagination/index.tsx
  src/pages/_app.tsx
  src/pages/activities.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
  src/pages/test.tsx
Labels: ♻️refactor

#34 ✨ JE-11-feat:dropdown
  .husky/prepare-commit-msg
  public/icon/arrowDown.svg
  src/components/dropdown/DropdownBody.tsx
  src/components/dropdown/DropdownButton.tsx
  src/components/dropdown/DropdownItem.tsx
  src/components/dropdown/index.tsx
  src/hooks/useClickOutside.ts
Labels: ✨feat

#32 ✨ JE-37-feat: 마이페이지 사이드 바 탭 구현
  public/icon/logout.svg
  src/components/commons/Footer/index.tsx
  src/components/commons/Header/index.tsx
  src/components/mypage/Info.tsx
  src/components/mypage/MenuToggle.tsx
  src/components/mypage/MyActivities.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/components/mypage/ReservationList.tsx
  src/components/mypage/ReservationState.tsx
  src/context/TabContext.tsx
  src/context/index.tsx
  src/hooks/index.tsx
  src/hooks/useMediaQeury.ts
  src/libs/utils/Icon.tsx
  src/pages/index.tsx
  src/pages/mypage.tsx
  src/pages/mypage/_components/ProfileSideBar.tsx
  src/pages/mypage/index.tsx
Labels: ✨feat

#35 ✨ JE-51-feat: modal 수정
  src/components/commons/Modal/Close.tsx
  src/components/commons/Modal/Root.tsx
  src/components/commons/Modal/Trigger.tsx
Labels: ✨feat

#37 🐛 JE-53-hotfix:dropdown 외부클릭감지 동작 오류 수정
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Dropdown/DropdownItem.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/mypage/ReservationState.tsx
  src/hooks/useClickOutside.ts
Labels: 🐛fix
