Repository joraeng-e/trip.zip, pull requests merged in 2024-08, with the labels that each got.

#39 ♻️ JE-54-refactor: input error animation 적용
  src/components/commons/Footer/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/PasswordInput.tsx
  src/components/commons/PageLayouts/index.tsx
  tailwind.config.ts
Labels: 💄ui, ♻️refactor

#41 ✨ JE-45-feat: activitydetail 페이지 구현(mockdata)
  public/data/activityDetail.json
  public/data/activityDetailReview.json
  src/components/ActivityDetail/Address.tsx
  src/components/ActivityDetail/BannerImage.tsx
  src/components/ActivityDetail/Description.tsx
  src/components/ActivityDetail/Review.tsx
  src/components/ActivityDetail/ReviewCard.tsx
  src/components/ActivityDetail/Title.tsx
  src/components/ActivityDetail/index.tsx
  src/pages/activity/[activityid].tsx
  src/types/api/activities.d.ts
Labels: ✨feat

#42 ✨ JE-56-feat: 내 정보 수정 구현
  src/components/commons/Footer/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/mypage/Info.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/libs/api/user.ts
  src/libs/axiosInstance.ts
  src/libs/utils/cookie.ts
  src/libs/utils/schemas/myInfoSchema.ts
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/styles/globals.css
  src/types/api/users.d.ts
Labels: ✨feat

#44 ♻️ JE-58-refactor: 비밀번호 유효성 추가
  src/libs/utils/schemas/loginSchema.ts
  src/libs/utils/schemas/signupSchema.ts
Labels: ♻️refactor

#45 ✨ JE-59-feat: 메타태그 설정
  src/pages/_document.tsx
Labels: ✨feat

#43 ✨JE-34-feat: trip registration page
  public/icon/minusTimeIcon.svg
  public/icon/plusIcon.svg
  public/icon/plusTimeIcon.svg
  public/icon/timeSeparatoricon.svg
  public/icon/xIcon.svg
  src/components/ActivitiyForm/FormComponents/DateTime.tsx
  src/components/ActivitiyForm/FormComponents/ImageUpload.tsx
  src/components/ActivitiyForm/index.tsx
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Footer/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/Textarea.tsx
  src/components/commons/Select/SelectList.tsx
  src/components/commons/Select/SelectOption.tsx
  src/components/commons/Select/index.tsx
  src/libs/constants/categories.ts
  src/libs/utils/Icon.tsx
  src/libs/utils/schemas/activitiesSchema.ts
  src/pages/mypage.tsx
  src/styles/globals.css
  src/types/api/activities.d.ts
  tailwind.config.ts
Labels: ✨feat

#46 ✨ JE-57-feat: 쿼리 스트링 업데이트
  __tests__/components/Pagination.test.tsx
  src/components/ActivityDetail/Review.tsx
  src/components/activities/ActivitiyGrid/Card.tsx
  src/components/activities/ActivitiyGrid/index.tsx
  src/components/activities/CategoryMenu.tsx
  src/components/activities/Dropdown.tsx
  src/components/activities/PopularActivities/Card.tsx
  src/components/activities/PopularActivities/index.tsx
  src/components/activities/Search/SearchBox.tsx
  src/components/commons/Pagination/Buttons.tsx
  src/components/commons/Pagination/index.tsx
  src/hooks/useIntersectionObserver.ts
  src/pages/activities.tsx
  tailwind.config.ts
Labels: ✨feat

#48 ✨ JE-38-feat: 내 체험 관리 페이지
  public/icon/starOnIcon.svg
  src/components/ActivitiyForm/index.tsx
  src/components/activitiesManagement/MyCard.tsx
  src/components/mypage/MyActivities.tsx
  src/pages/mypage.tsx
Labels: ✨feat

#49 ✨ JE-50-feat:booking status page
  public/icon/doubleArrowNext.svg
  public/icon/doubleArrowPrev.svg
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/mypage/BookingCalendar/BookingCalendar.tsx
  src/components/mypage/BookingCalendar/BookingStatusTag.tsx
  src/components/mypage/ReservationState.tsx
  src/components/mypage/ReservationStatus.tsx
  src/libs/api/myActivities.ts
  src/libs/utils/Icon.tsx
  src/libs/utils/dateUtils.ts
  src/pages/mypage.tsx
  src/types/api/my-activities.d.ts
Labels: ✨feat

#53 ♻️ JE-66-refactor: 페이지 메타태그 설정
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/activities.tsx
  src/pages/activity/[activityid].tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: ♻️refactor

#51 ♻️ JE-63-refactor: Carousel
  src/components/activities/Carousel/Control.tsx
  src/components/activities/Carousel/Root.tsx
  src/components/activities/Carousel/Slides.tsx
  src/components/activities/Carousel/index.tsx
  src/components/commons/Carousel/Indicator.tsx
  src/components/commons/Carousel/Navigator.tsx
  src/components/commons/Carousel/Root.tsx
  src/components/commons/Carousel/Slide.tsx
  src/components/commons/Carousel/hooks/useCarouselDrag.ts
  src/components/commons/Carousel/index.ts
  src/components/commons/Pagination/index.tsx
Labels: ♻️refactor

#54 ♻️ JE-68-refactor: 내 프로필 컴포넌트 -> 페이지 변경
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/components/mypage/ReservationList.tsx
  src/pages/mypage.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/info.tsx
  src/pages/mypage/myActivities.tsx
  src/pages/mypage/reservationList.tsx
  src/pages/mypage/reservationStatus.tsx
Labels: ♻️refactor

#55 ✨ JE-69-feat: userInfo 정보 반영 및 드롭박스
  src/components/commons/Header/_components/LoggedInHeader.tsx
Labels: ✨feat

#56 ✨ JE-67-feat: Notification UI
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Header/_components/Notification/NotificationItem.tsx
  src/components/commons/Header/_components/Notification/NotificationPopup.tsx
  src/components/commons/Header/_components/Notification/index.tsx
  src/libs/api/myNotifications.ts
  src/libs/utils/dateUtils.ts
Labels: ✨feat

#52 ✨ JE-60-feat: 내 프로필 등록 및 수정(feat. 이미지)
  src/components/commons/Modal/Root.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ProfileImage.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/libs/api/user.ts
  src/libs/utils/schemas/myInfoSchema.ts
  src/pages/mypage/info.tsx
  src/styles/globals.css
Labels: ✨feat, 🖐🏻 hold

#50 ♻️ JE-64-refactor:dropdown
  src/components/activities/Dropdown.tsx
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Dropdown/DropdownItem.tsx
  src/components/commons/Dropdown/index.tsx
Labels: ♻️refactor

#58 ✨ JE-72-feat: 페이지 전환 시 애니메이션 효과 적용
  src/components/commons/Header/index.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/context/TabContext.tsx
  src/pages/activity/[activityid].tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/info.tsx
  src/styles/globals.css
Labels: ✨feat

#60 ✨ JE-73-feat: 토스트 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/commons/Toast/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: ✨feat

#59 ✨ JE-71-feat: 알림 무한 스크롤 & 삭제
  src/components/commons/Header/_components/Notification/NotificationItem.tsx
  src/components/commons/Header/_components/Notification/NotificationPopup.tsx
  src/components/commons/Header/_components/Notification/hooks/useNotificationDrag.ts
  src/components/commons/Header/_components/Notification/index.tsx
  src/pages/activities.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨feat

#61 ♻️ JE-75-refactor: modal or alert 토스트로 변경
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/mypage/ProfileImage.tsx
  src/pages/login.tsx
  src/pages/mypage/index.tsx
  src/pages/signup.tsx
Labels: ♻️refactor

#63 ✨ JE-79-feat: 체험 삭제하기
  src/components/ActivitiyForm/DateTime.tsx
  src/components/ActivitiyForm/ImageUpload.tsx
  src/components/activitiesManagement/MyCard.tsx
  src/libs/utils/schemas/activitiesSchema.ts
  src/pages/mypage/myActivities/index.tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
Labels: ✨feat

#65 ✨ JE-76-feat: 내 예약 내역 구현(feat.무한스크롤 + 드롭다운 정렬)
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/mypage/NoActivity.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/libs/api/myReservations.ts
  src/pages/mypage/reservationList.tsx
  src/types/api/my-reservations.d.ts
Labels: ✨feat

#62 ✨ JE-78-feat: toast UI 및 option, onClose 추가
  package.json
  pnpm-lock.yaml
  public/lottie/check.json
  public/lottie/error.json
  src/components/commons/Toast/index.tsx
  src/pages/_app.tsx
  src/styles/ToastStyle.tsx
Labels: ✨feat, 💄ui

#64 ✨ JE-36-feat: activity detail page
  package.json
  pnpm-lock.yaml
  public/data/activityDetail.json
  public/data/activityDetailReview.json
  public/data/activityDetailSchedule.json
  public/icon/emoji/automobileEmoji.svg
  public/icon/emoji/couchLampEmoji.svg
  public/icon/emoji/gemEmoji.svg
  public/icon/emoji/heartEmoji.svg
  public/icon/emoji/huggingFaceEmoji.svg
  public/icon/emoji/moneyWingEmoji.svg
  public/icon/emoji/nationalParkEmoji.svg
  public/icon/emoji/partyEmoji.svg
  public/icon/emoji/soccerBallEmoji.svg
  public/icon/emoji/spongeEmoji.svg
  public/icon/emoji/starEmoji.svg
  public/icon/locationIcon.svg
  src/components/ActivityDetail/Address.tsx
  src/components/ActivityDetail/Banner/BannerImage.tsx
  src/components/ActivityDetail/Banner/BannerImageModal.tsx
  src/components/ActivityDetail/Banner/BlurBannerImage.tsx
  src/components/ActivityDetail/Banner/ImageCounter.tsx
  src/components/ActivityDetail/Banner/ImageNavButton.tsx
  src/components/ActivityDetail/Banner/MobileBannerImage.tsx
  src/components/ActivityDetail/Banner/ThumbnailImage.tsx
  src/components/ActivityDetail/BannerImage.tsx
  src/components/ActivityDetail/BaseModal.tsx
  src/components/ActivityDetail/Description.tsx
  src/components/ActivityDetail/DetailContent/ActivityTabs.tsx
  src/components/ActivityDetail/DetailContent/Address.tsx
  src/components/ActivityDetail/DetailContent/Description.tsx
  src/components/ActivityDetail/DetailContent/Title.tsx
  src/components/ActivityDetail/DetailContent/index.tsx
  src/components/ActivityDetail/ExpandableText.tsx
  src/components/ActivityDetail/Reivew/ReviewCard.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/ActivityDetail/Reivew/StarRating.tsx
  src/components/ActivityDetail/Reivew/index.tsx
  src/components/ActivityDetail/Reservation/MobileReservationFooter.tsx
  src/components/ActivityDetail/Reservation/MobileReservationModal.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/ActivityDetail/Review.tsx
  src/components/ActivityDetail/ReviewCard.tsx
  src/components/ActivityDetail/Title.tsx
  src/components/ActivityDetail/index.tsx
  src/components/commons/KakaoMap/index.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/commons/ReviewTag/index.tsx
  src/hooks/useExtractTags.ts
  src/libs/utils/Icon.tsx
  src/pages/activity/[activityid].tsx
  src/styles/CalendarStyle.tsx
  src/styles/globals.css
  src/types/api/activities.d.ts
Labels: ✨feat

#67 ✨ JE-74-feat: 소셜 회원가입/로그인 구현
  public/imgs/google.png
  public/imgs/kakao.png
  src/components/socialAuth/SocialLogin.tsx
  src/components/socialAuth/SocialSignup.tsx
  src/libs/api/oauth.ts
  src/libs/axiosInstance.ts
  src/libs/constants/auth.ts
  src/libs/utils/randomNickname.ts
  src/pages/login/index.tsx
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
  src/pages/signup/index.tsx
  src/pages/signup/oauth/google.tsx
  src/pages/signup/oauth/kakao.tsx
  src/types/api/oauth.d.ts
Labels: ✨feat

#70 ✨ JE-81-feat: 비행기 로딩 화면 구현
  public/icon/cloud.svg
  src/components/commons/Loading/index.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/mypage/MenuToggle.tsx
  src/hooks/useLoading.ts
  src/libs/utils/Icon.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/pages/test.tsx
Labels: ✨feat

#71 🐛 JE-86-fix: lottie 에러
  src/components/commons/Toast/index.tsx
Labels: 🐛fix

#68 ✨ JE-65-feat:calender improvement
  public/icon/xIcon.svg
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Dropdown/DropdownItem.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/mypage/BookingCalendar/BookingCalendar.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx
  src/components/mypage/BookingCalendar/BookingStatusTag.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/pages/mypage/calendar.tsx
  src/pages/mypage/reservationStatus.tsx
Labels: ✨feat

#66 ✨ JE-62-feat: 체험 수정 페이지
  public/icon/kebabIcon.svg
  src/components/ActivitiyForm/DateTime.tsx
  src/components/ActivitiyForm/ImageUpload.tsx
  src/components/activitiesManagement/MyCard.tsx
  src/libs/api/myActivities.ts
  src/libs/utils/schemas/activitiesSchema.ts
  src/pages/mypage/myActivities/editForm/[id].tsx
  src/pages/mypage/myActivities/index.tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
  src/types/api/activities.d.ts
  src/types/datetype.ts
Labels: ✨feat

#73 ♻️ JE-88-refactor: 마이페이지 수정 및 로딩화면 적용
  public/data/activityDetail.json
  public/lottie/empty.json
  public/lottie/loading.json
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Loading/DotLoading.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/mypage/MenuToggle.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/NoActivity.tsx
  src/components/mypage/ProfileImage.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/libs/utils/schemas/myInfoSchema.ts
  src/pages/activity/[activityid].tsx
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
  src/pages/mypage/calendar.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/myActivities/index.tsx
  src/pages/mypage/reservationList.tsx
  src/pages/signup/oauth/google.tsx
  src/pages/signup/oauth/kakao.tsx
  src/styles/globals.css
Labels: ♻️refactor

#75 ✨ JE-89-feat: 소셜 로그인 마이페이지 patch 요소 수정
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/PasswordInput.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
  src/pages/mypage/index.tsx
Labels: ✨feat

#76 ✨ JE-85-feat: activity detail api 연동 및 UI 수정
  public/imgs/baseProfile.png
  public/lottie/emptyReview.json
  src/components/ActivityDetail/Banner/BannerImage.tsx
  src/components/ActivityDetail/Banner/BannerImageModal.tsx
  src/components/ActivityDetail/BaseModal.tsx
  src/components/ActivityDetail/DetailContent/index.tsx
  src/components/ActivityDetail/ExpandableText.tsx
  src/components/ActivityDetail/Reivew/ReviewCard.tsx
  src/components/ActivityDetail/Reivew/ReviewList.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/ActivityDetail/Reivew/index.tsx
  src/components/commons/ReviewTag/index.tsx
  src/libs/api/activities.ts
  src/pages/activity/[activityid].tsx
Labels: ✨feat

#74 ✨JE-83-feat:review modal
  public/imgs/empty.webp
  public/logo/tripZip.webp
  public/logo/tripzipFavicon.webp
  src/components/commons/Header/index.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/components/mypage/ReservationList/ReviewModal/Rating.tsx
  src/components/mypage/ReservationList/ReviewModal/ReviewModal.tsx
  src/libs/api/myActivities.ts
  src/libs/utils/formatNumber.ts
  src/pages/_document.tsx
  src/pages/mypage/calendar.tsx
  src/pages/mypage/reservationList.tsx
Labels: ✨feat

#77 ✨ JE-82-feat: 랜딩 페이지
  public/imgs/plane-7206856_1920.jpg
  public/imgs/tripzip.png
  public/lottie/plane.json
  public/lottie/route.json
  public/lottie/travel.json
  public/lottie/travelling.json
  src/components/commons/Button/StartButton.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/landing/InfiniteCarousel.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ✨feat

#79 ♻️ JE-97-refactor: 폰트 최적화
  public/font/Pretendard-Bold.subset.woff2
  public/font/Pretendard-Light.subset.woff2
  public/font/Pretendard-Medium.subset.woff2
  public/font/Pretendard-Regular.subset.woff2
  public/font/Pretendard-SemiBold.subset.woff2
  src/components/commons/PageLayouts/index.tsx
  src/styles/globals.css
Labels: ♻️refactor

#80 ✨ JE-92-feat: 다크모드 구현
  public/icon/bedIcon.svg
  public/icon/logout.svg
  public/icon/notificationIcon.svg
  public/icon/timeSeparatoricon.svg
  public/icon/xIcon.svg
  public/lottie/empty.json
  src/components/ActivitiyForm/DateTime.tsx
  src/components/ActivitiyForm/ImageUpload.tsx
  src/components/ActivityDetail/BaseModal.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/activities/ActivitiyGrid/Card.tsx
  src/components/activities/CategoryMenu.tsx
  src/components/activities/Dropdown.tsx
  src/components/activities/PopularActivities/index.tsx
  src/components/activities/Search/SearchBox.tsx
  src/components/activities/Search/SearchResult.tsx
  src/components/activitiesManagement/MyCard.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Dropdown/DropdownBody.tsx
  src/components/commons/Dropdown/DropdownButton.tsx
  src/components/commons/Dropdown/DropdownItem.tsx
  src/components/commons/Header/_components/DarkMode/index.tsx
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Header/_components/Notification/NotificationPopup.tsx
  src/components/commons/Header/_components/Notification/index.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/PasswordInput.tsx
  src/components/commons/Input/Textarea.tsx
  src/components/commons/Modal/Content.tsx
  src/components/commons/Pagination/Buttons.tsx
  src/components/commons/Select/SelectList.tsx
  src/components/commons/Select/SelectOption.tsx
  src/components/commons/Select/index.tsx
  src/components/mypage/MenuToggle.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/NoActivity.tsx
  src/components/mypage/ProfileImage.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/components/socialAuth/SocialLogin.tsx
  src/components/socialAuth/SocialSignup.tsx
  src/context/DarkModeContext.tsx
  src/pages/_app.tsx
  src/pages/activities.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/myActivities/index.tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨feat

#86 ✨ JE-98-feat: 체험 추천 페이지
  public/imgs/recommend/food-tour-changjun.png
  public/imgs/recommend/food-tour-hongdae.png
  public/imgs/recommend/food-tour-mapo.png
  public/imgs/recommend/seoul-commentary.png
  public/imgs/recommend/seoul-culture.png
  public/imgs/recommend/seoul-hanok.png
  public/imgs/recommend/summer-concert.png
  public/imgs/recommend/summer-edu.png
  public/imgs/recommend/summer-festival.png
  src/components/activities/Carousel/Slides.tsx
  src/components/activities/Carousel/index.tsx
  src/components/activities/CategoryMenu.tsx
  src/components/activities/Layout.tsx
  src/components/activities/PopularActivities/index.tsx
  src/components/commons/Header/_components/Notification/NotificationPopup.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/commons/Pagination/Buttons.tsx
  src/components/recommend/ActivityGuide.tsx
  src/components/recommend/BannerImage.tsx
  src/components/recommend/Introduction.tsx
  src/components/recommend/Layout.tsx
  src/components/recommend/RelatedInfo.tsx
  src/libs/api/activities.ts
  src/pages/recommend/food-tour.tsx
  src/pages/recommend/seoul.tsx
  src/pages/recommend/summer.tsx
  src/styles/globals.css
Labels: ✨feat

#84 ♻️ JE-95-refactor: activity detail page
  package.json
  pnpm-lock.yaml
  public/lottie/check.json
  src/components/ActivityDetail/Banner/BannerImage.tsx
  src/components/ActivityDetail/Banner/ThumbnailImage.tsx
  src/components/ActivityDetail/BaseModal.tsx
  src/components/ActivityDetail/DetailContent/ActivityTabs.tsx
  src/components/ActivityDetail/DetailContent/Address.tsx
  src/components/ActivityDetail/DetailContent/Description.tsx
  src/components/ActivityDetail/DetailContent/Title.tsx
  src/components/ActivityDetail/DetailContent/index.tsx
  src/components/ActivityDetail/Reivew/index.tsx
  src/components/ActivityDetail/Reservation/MobileReservationFooter.tsx
  src/components/ActivityDetail/Reservation/MobileReservationModal.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/commons/Header/_components/LoggedInHeader.tsx
  src/components/commons/Header/_components/LoggedOutHeader.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/Modal/Content.tsx
  src/libs/api/activities.ts
  src/pages/activity/[activityid].tsx
  src/pages/mypage/myActivities/index.tsx
  src/styles/CalendarStyle.tsx
Labels: ✨feat, ♻️refactor

#85 ✨ JE-102-feat: 날짜 지나면 카드 예약 취소 처리
  src/components/activitiesManagement/MyCard.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/pages/mypage/reservationList.tsx
Labels: ✨feat

#87 ♻️ JE-107-fix: 프로필 변경 이슈 해결
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/pages/mypage/index.tsx
Labels: ♻️refactor

#89 ♻️ JE-100-refactor: 소셜 로그인 계정 없을 때 오류 처리
  src/components/auths/Logo.tsx
  src/components/commons/Header/_components/LoggedOutHeader.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/Input/Input.tsx
  src/components/commons/Input/PasswordInput.tsx
  src/pages/login/index.tsx
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
  src/pages/signup/index.tsx
Labels: ♻️refactor

#83 ♻️ JE-91-refactor: 폼 마크다운 구현
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/activitiesManagement/MyCard.tsx
  src/pages/_app.tsx
  src/pages/mypage/myActivities/editForm/[id].tsx
  src/pages/mypage/myActivities/index.tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
  src/styles/globals.css
Labels: ♻️refactor

#88 ✨ JE-106-feat: PWA Setting
  .eslintignore
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  public/logo/logo192.png
  public/logo/logo512.png
  public/manifest.json
  src/pages/_document.tsx
Labels: ✨feat

#90 🐛 hotfix-nextConfig-fix: mjs 파일 제거
  next.config.mjs
Labels: 🐛fix

#91 ✨ JE-108-feat: 개인정보 처리방침, FAQ 페이지 구현
  src/pages/faq.tsx
  src/pages/index.tsx
  src/pages/privacy-policy.tsx
  src/pages/test.tsx
Labels: ✨feat

#92 ♻️ JE-111-refactor: 버튼 위치 및 크기 조정
  src/pages/mypage/myActivities/editForm/[id].tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
Labels: ♻️refactor

#94 💄 JE-113-ui: 다크모드 적용 및 UI 수정
  public/icon/locationIcon.svg
  src/components/ActivityDetail/Banner/BannerImage.tsx
  src/components/ActivityDetail/DetailContent/ActivityTabs.tsx
  src/components/ActivityDetail/DetailContent/Address.tsx
  src/components/ActivityDetail/DetailContent/Description.tsx
  src/components/ActivityDetail/DetailContent/Title.tsx
  src/components/ActivityDetail/ExpandableText.tsx
  src/components/ActivityDetail/Reivew/ReviewCard.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/ActivityDetail/Reservation/MobileReservationFooter.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/commons/Header/_components/Notification/NotificationItem.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/ReviewTag/index.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/pages/mypage/myActivities/editForm/[id].tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
  src/styles/CalendarStyle.tsx
  src/styles/globals.css
Labels: 💄ui

#95 ♻️ JE-109-refactor: form 리팩토링 및 ui 수정
  src/components/ActivitiyForm/ImageUpload.tsx
  src/components/activitiesManagement/MyCard.tsx
  src/pages/index.tsx
  src/pages/mypage/myActivities/editForm/[id].tsx
  src/pages/mypage/myActivities/registerForm/index.tsx
Labels: ♻️refactor

#98 ✨ JE-114-feat: detail recommend
  package.json
  pnpm-lock.yaml
  src/components/ActivityDetail/BaseModal.tsx
  src/components/ActivityDetail/DetailContent/ActivityTabs.tsx
  src/components/ActivityDetail/DetailContent/Address.tsx
  src/components/ActivityDetail/DetailContent/Title.tsx
  src/components/ActivityDetail/Recommend/ArrowButton.tsx
  src/components/ActivityDetail/Recommend/EmblaCarousel.tsx
  src/components/ActivityDetail/Recommend/index.tsx
  src/components/ActivityDetail/Reivew/ReviewCard.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/ActivityDetail/Reservation/MobileReservation.tsx
  src/components/ActivityDetail/Reservation/MobileReservationFooter.tsx
  src/components/ActivityDetail/Reservation/MobileReservationModal.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/commons/KakaoMap/index.tsx
  src/components/commons/ReviewTag/index.tsx
  src/pages/activity/[activityid].tsx
  src/types/api/activities.d.ts
Labels: ✨feat

#99 ♻️ JE-117-refactor: 헤더 리팩토링
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/commons/Header/_components/DarkModeToggleButton/index.tsx
  src/components/commons/Header/index.tsx
  src/components/commons/Loading/index.tsx
  src/components/commons/PageLayouts/index.tsx
  src/components/commons/Toast/index.tsx
  src/components/mypage/ProfileSideBar.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
  src/hooks/useAuthBoundary.ts
  src/hooks/useLoading.ts
  src/libs/constants/auth.ts
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
Labels: ♻️refactor

#97 ✨ JE-110-feat: PWA Notification
  .eslintignore
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  public/firebase-messaging-sw.js
  public/font/Pretendard-Bold.subset.woff2
  public/font/Pretendard-Light.subset.woff2
  public/font/Pretendard-Medium.subset.woff2
  public/font/Pretendard-Regular.subset.woff2
  public/font/Pretendard-SemiBold.subset.woff2
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx
  src/libs/api/myNotifications.ts
  src/libs/firebase.js
  src/pages/_offline.tsx
  src/styles/globals.css
Labels: ✨feat

#96 ♻️JE-103-refactor:calendar componentization
  src/components/mypage/BookingCalendar/BookingCalendar.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx/BookingDetailCard.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx/BookingDetailModal.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx/BookingStatusTag.tsx
  src/components/mypage/BookingCalendar/BookingDetailModal.tsx/ConfirmationModal.tsx
  src/components/mypage/BookingCalendar/Calendar/ControlBar.tsx
  src/components/mypage/BookingCalendar/Calendar/DateCell.tsx
  src/components/mypage/BookingCalendar/Calendar/generateCalendar.ts
  src/components/mypage/BookingCalendar/Calendar/index.tsx
  src/pages/mypage/calendar.tsx
Labels: ♻️refactor

#103 ♻️ JE-119-refactor: activities page
  public/icon/backIcon.svg
  public/icon/searchIcon.svg
  src/components/activities/CategoryMenu.tsx
  src/components/activities/Dropdown.tsx
  src/components/activities/PopularActivities/index.tsx
  src/components/activities/Search/SearchBox.tsx
  src/components/commons/Carousel/Root.tsx
  src/components/recommend/BannerImage.tsx
  src/components/recommend/GoBackButton.tsx
  src/components/recommend/Introduction.tsx
  src/libs/utils/Icon.tsx
  src/pages/activities.tsx
  src/pages/recommend/food-tour.tsx
  src/pages/recommend/seoul.tsx
  src/pages/recommend/summer.tsx
Labels: ♻️refactor

#102 ♻️ JE-118-refactor: detail page
  src/components/ActivityDetail/Banner/BannerButton.tsx
  src/components/ActivityDetail/Banner/BannerImage.tsx
  src/components/ActivityDetail/Banner/ImageGallery.tsx
  src/components/ActivityDetail/Banner/MobileBannerImage.tsx
  src/components/ActivityDetail/DetailContent/ActivityTabs.tsx
  src/components/ActivityDetail/DetailContent/Address.tsx
  src/components/ActivityDetail/DetailContent/Description.tsx
  src/components/ActivityDetail/DetailContent/Title.tsx
  src/components/ActivityDetail/DetailContent/Title/Address.tsx
  src/components/ActivityDetail/DetailContent/Title/Category.tsx
  src/components/ActivityDetail/DetailContent/Title/DropdownMenu.tsx
  src/components/ActivityDetail/DetailContent/Title/Rating.tsx
  src/components/ActivityDetail/DetailContent/Title/TitleText.tsx
  src/components/ActivityDetail/DetailContent/Title/index.tsx
  src/components/ActivityDetail/DetailContent/index.tsx
  src/components/ActivityDetail/Recommend/ArrowButton.tsx
  src/components/ActivityDetail/Recommend/EmblaCarousel.tsx
  src/components/ActivityDetail/Recommend/RecommendCard.tsx
  src/components/ActivityDetail/Recommend/RecommendCarousel.tsx
  src/components/ActivityDetail/Recommend/index.tsx
  src/components/ActivityDetail/Reivew/NoReview.tsx
  src/components/ActivityDetail/Reivew/ReviewCard/ReviewRating.tsx
  src/components/ActivityDetail/Reivew/ReviewCard/ReviewUser.tsx
  src/components/ActivityDetail/Reivew/ReviewCard/index.tsx
  src/components/ActivityDetail/Reivew/ReviewTitle.tsx
  src/components/ActivityDetail/Reivew/index.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ActivityDetail.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ReservationCard.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ReservationDetails.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ReservationUser.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/index.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule.tsx
  src/components/ActivityDetail/Reservation/Schedule/Schedule.tsx
  src/components/ActivityDetail/Reservation/Schedule/ScheduleButton.tsx
  src/components/ActivityDetail/Reservation/Schedule/ScheduleList.tsx
  src/components/commons/ReviewTag/index.tsx
  src/pages/activity/[activityid].tsx
  src/styles/globals.css
Labels: 💄ui, ♻️refactor

#105 ♻️ JE-121-ui: 예약 취소 버튼 수정
  src/components/commons/Input/Textarea.tsx
  src/components/mypage/ReservationList/ReservationCard.tsx
Labels: 💄ui

#106 🐛 hotfix-notification-fix: 알림 복원
  src/components/ActivityDetail/Reservation/Schedule/Schedule.tsx
  src/styles/globals.css
Labels: 🐛fix

#108 📦 JE-124-chore: rehype-raw 플러그인 설치 및 적용
  package.json
  pnpm-lock.yaml
  src/components/ActivityDetail/DetailContent/Description.tsx
  src/components/mypage/activityform/MarkdownEditor.tsx
Labels: 📦 chore

#107 ♻️ JE-123-refactor: error 처리 및 상수 분리
  src/components/mypage/MenuToggle.tsx
  src/components/mypage/MyPageLayout.tsx
  src/libs/api/activities.ts
  src/libs/api/user.ts
  src/libs/axiosInstance.ts
  src/libs/constants/auth.ts
  src/pages/login/oauth/google.tsx
  src/pages/login/oauth/kakao.tsx
  src/pages/signup/index.tsx
  src/pages/signup/oauth/google.tsx
  src/pages/signup/oauth/kakao.tsx
Labels: ♻️refactor

#109 ♻️ JE-122-refactor: 멘토님 피드백 반영
  src/components/mypage/BookingCalendar/Calendar/index.tsx
  src/pages/mypage/calendar.tsx
Labels: ♻️refactor

#104 ✨ JE-120-feat: review tag
  public/lottie/emptyReview.json
  src/components/ActivityDetail/Recommend/index.tsx
  src/components/ActivityDetail/Reivew/NoReview.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ActivityDetail.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/ReservationCard.tsx
  src/components/ActivityDetail/Reservation/ReservationConfirmation/index.tsx
  src/components/ActivityDetail/Reservation/ReservationSideBar.tsx
  src/components/ActivityDetail/Reservation/Schedule/Schedule.tsx
  src/components/commons/Modal/Root.tsx
  src/components/commons/ReviewTag/index.tsx
  src/components/mypage/ReservationList/ReviewModal/ReviewModal.tsx
  src/hooks/useExtractTags.ts
  src/pages/activity/[activityid].tsx
Labels: ✨feat, 💄ui

#110 📝 JE-125-docs: README 작성
  README.md
  public/imgs/mainImage.png
  public/imgs/stackImage.png
Labels: 📝docs
